version: '3'
services: 
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
  flask:
    build: ./flask
    restart: always
    expose:
      - 3031
    volumes:
      - ./flask/app:/home/app
      - ./flask/uwsgi.ini:/home/uwsgi.ini
    command: uwsgi --ini /home/uwsgi.ini
    env_file:
      - .env